# Install packages
- name: Tap a Homebrew repository, state present
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_tap_list }}"
  register: brew_tap

- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_list }}"
  when: brew_tap

- name: Install cask
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_cask_list }}"
  register: cask_install

- name: install vscode plugins
  ansible.builtin.command:
    cmd: "code --install-extension {{ item }}"
    creates: "~/.vscode/extensions/{{ item }}-*"
  loop: "{{ vscode_list }}"
  when: cask_install
